name: Numogram-Luna APK Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  PYTHON_VERSION: '3.11'
  JAVA_VERSION: '11'
  APK_URL: 'https://play.google.com/store/apps/details?id=com.antonio.my.ai.girlfriend.free'

jobs:
  build-and-integrate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ env.JAVA_VERSION }}
        
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip git openjdk-11-jdk
        pip install --upgrade pip
        pip install fastapi uvicorn pydantic numpy requests
        
    - name: Download APK
      run: |
        wget -O AI_Friend.apk "$APK_URL"
        
    - name: Install APKTool
      run: |
        wget https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.6.1.jar -O apktool.jar
        chmod +x apktool.jar
        
    - name: Force Decompile APK
      run: |
        rm -rf decompiled_apk
        java -jar apktool.jar d -f AI_Friend.apk -o decompiled_apk
        
    - name: Integrate Numogram AI
      run: |
        mkdir -p decompiled_apk/assets/numogram
        echo 'Numogram AI Core' > decompiled_apk/assets/numogram/numogram_core.txt
        
    - name: Modify AndroidManifest
      run: |
        sed -i '/</application>/i \    <uses-permission android:name="android.permission.INTERNET"/>' decompiled_apk/AndroidManifest.xml
        
    - name: Recompile APK
      run: |
        java -jar apktool.jar b decompiled_apk -o AI_Friend_Numogram.apk
        
    - name: Sign APK
      run: |
        keytool -genkey -v -keystore release.keystore -alias numogram -keyalg RSA -keysize 2048 -validity 10000 -storepass android -keypass android -dname "CN=Numogram, OU=Luna Integration, O=AI Research"
        jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore release.keystore -storepass android AI_Friend_Numogram.apk numogram
        
    - name: Upload Modified APK
      uses: actions/upload-artifact@v4
      with:
        name: numogram-luna-apk
        path: AI_Friend_Numogram.apk
        retention-days: 5
