name: Numogram-Luna Integration and APK Repackage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 8000:8000

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python for Numogram AI backend
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip openjdk-11-jdk
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pydantic numpy

      # Step 3: Set up Docker for API container
      - name: Set up Docker
        run: |
          echo "FROM python:3.11-slim" > Dockerfile
          echo "WORKDIR /app" >> Dockerfile
          echo "COPY . /app" >> Dockerfile
          echo "RUN pip install fastapi uvicorn pydantic numpy" >> Dockerfile
          echo 'CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]' >> Dockerfile

      - name: Build Docker Image
        run: docker build -t numogram-luna-app .

      - name: Run Docker Container (optional during workflow)
        run: docker run -d -p 8000:8000 numogram-luna-app

      # Step 4: Install Java and APKTool for APK decompilation
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install APKTool
        run: |
          wget https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.6.1.jar -O apktool.jar
          wget https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool -O apktool
          chmod +x apktool
          sudo mv apktool* /usr/local/bin/

      # Step 5: Decompile, Inject Numogram, and Repackage APK
      - name: Decompile APK
        run: |
          java -jar apktool.jar d AI_Friend.apk -o AI_Friend_decompiled

      - name: Inject Numogram AI Code
        run: |
          cp -r ./numogram_code/* AI_Friend_decompiled/smali/

      - name: Recompile APK
        run: |
          java -jar apktool.jar b AI_Friend_decompiled -o AI_Friend_Modified.apk

      # Step 6: Upload the modified APK as an artifact
      - name: Upload Repackaged APK
        uses: actions/upload-artifact@v4
        with:
          name: AI_Friend_Modified
          path: AI_Friend_Modified.apk
